[package]
name = "{{project-name}}"
authors = [
    "{{authors}}"
]
version = "0.1.0-rc1"{% if proc_macros %}  # Keep in sync{% endif %}
edition = "2018"

license = "Zlib OR MIT OR Apache-2.0"
repository = "https://github.com/danielhenrymantilla/{{project-name}}.rs"
documentation = "https://docs.rs/{{project-name}}"
readme = "README.md"

# description = "…"
# keywords = []

[features]
better-docs = []  # allowed to break MSRV
ui-tests = ["better-docs"]
{% if proc_macros %}
[dependencies.{{project-name}}-proc_macros]
path = "src/proc_macros"
version = "0.1.0-rc1"  # Keep in sync
{% endif %}
[dev-dependencies]

[workspace]
{% if proc_macros %}members = [
    "src/proc_macros",
]
{% endif %}
[package.metadata.docs.rs]
all-features = true
