[package]
name = "{{crate_name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro-hack = "0.5.11"  # For procedural macros in expression position.

[dependencies.proc-macro]
package = "{{crate_name}}_proc-macro"
version = "0.1.0"  # Same as package.version
path = "src/proc-macro"
