[placeholders.MSRV]
type = "string"
prompt = "Minimum Supported Rust Version?"
default = "1.42.0"
regex = '^\s*1\.\d\d\.0\s*$'

[placeholders.version]
type = "string"
prompt = "Initial package version?"
default = "0.1.0"
regex = '^\s*[0-9]+\.[0-9]+\.[0-9]+(?:-.*)?\s*$'

[placeholders.proc_macros]
type = "bool"
prompt = "Will you be defining procedural macros?"
default = true

[template]
ignore = [
    '.git',
    'rust-toolchain',
]

[conditional.'proc_macros == false']
ignore = [
    'src/proc_macros',
]
